# Generated by Django 5.1.15 on 2026-08-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='USER', help_text='From Authentik claim `role` (e.g. HR, USER)', max_length=50),
        ),
    ]
