# Generated by Django 5.1.15 on 2026-08-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='', help_text='From Authentik claim `role` (e.g. HR)', max_length=50),
        ),
    ]
