# Generated by Django 5.1.15 on 2026-08-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_user_role_no_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_code',
        ),
        migrations.RemoveField(
            model_name='division',
            name='division_code',
        ),
    ]
