# Generated by Django 5.1.15 on 2026-08-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_remove_division_department_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposition',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='jobposition',
            name='job_code',
        ),
    ]
