# Generated by Django 5.1.15 on 2026-08-16 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_user_line_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name_th', models.CharField(blank=True, max_length=20, null=True, verbose_name='คำนำหน้า (ไทย)')),
                ('first_name_th', models.CharField(max_length=100, verbose_name='ชื่อ (ไทย)')),
                ('last_name_th', models.CharField(max_length=100, verbose_name='นามสกุล (ไทย)')),
                ('title_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='คำนำหน้า (Eng)')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อ (Eng)')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='นามสกุล (Eng)')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, verbose_name='ชื่อเล่น')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='อีเมล')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='เบอร์โทรศัพท์')),
                ('phone_number1', models.CharField(blank=True, max_length=15, null=True, verbose_name='เบอร์โทรศัพท์สำรอง')),
                ('idcard', models.CharField(blank=True, max_length=13, null=True, verbose_name='เลขบัตรประชาชน')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='วันเกิด')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่บัตรประชาชน')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='จังหวัด')),
                ('amphure', models.CharField(blank=True, max_length=100, null=True, verbose_name='เขต/อำเภอ')),
                ('tambon', models.CharField(blank=True, max_length=100, null=True, verbose_name='แขวง')),
                ('zip', models.CharField(blank=True, max_length=5, null=True, verbose_name='รหัสไปรษณีย์')),
                ('address_present', models.TextField(blank=True, null=True, verbose_name='ที่อยู่ปัจจุบัน')),
                ('province_present', models.CharField(blank=True, max_length=100, null=True, verbose_name='จังหวัดปัจจุบัน')),
                ('amphure_present', models.CharField(blank=True, max_length=100, null=True, verbose_name='เขต/อำเภอปัจจุบัน')),
                ('tambon_present', models.CharField(blank=True, max_length=100, null=True, verbose_name='แขวงปัจจุบัน')),
                ('zip_present', models.CharField(blank=True, max_length=5, null=True, verbose_name='รหัสไปรษณีย์ปัจจุบัน')),
                ('marital_status', models.CharField(blank=True, max_length=10, null=True, verbose_name='สถานภาพ')),
                ('sex', models.CharField(blank=True, max_length=5, null=True, verbose_name='เพศ')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='candidate_photos/', verbose_name='รูปถ่าย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ผู้สมัคร',
                'verbose_name_plural': 'ผู้สมัคร',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อบริษัท')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': '1. ชื่อบริษัท',
                'verbose_name_plural': '1. ชื่อบริษัท (Master Data)',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ระดับพนักงาน')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': '3. ระดับพนักงาน',
                'verbose_name_plural': '3. ระดับพนักงาน (Master Data)',
            },
        ),
        migrations.CreateModel(
            name='WorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='สถานที่ทำงาน')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': '2. สถานที่ทำงาน',
                'verbose_name_plural': '2. สถานที่ทำงาน (Master Data)',
            },
        ),
        migrations.AlterField(
            model_name='department',
            name='division',
            field=models.ForeignKey(help_text='ฝ่ายที่ตำแหน่งนี้อยู่', on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='recruitment.division'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='current_headcount',
            field=models.PositiveIntegerField(default=0, help_text='จำนวนคนปัจจุบันในตำแหน่งนี้'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='description',
            field=models.TextField(blank=True, help_text='คำอธิบายของตำแหน่งนี้'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='target_headcount',
            field=models.PositiveIntegerField(default=0, help_text='ความจุของตำแหน่งนี้ (เพิ่มขึ้นเมื่อคำขออัตรากำลังถูกอนุมัติ)'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='approved_headcount',
            field=models.PositiveIntegerField(default=0, help_text='จำนวนคนที่ผู้ใช้งานของผู้ใช้งานนี้ของผู้ใช้งานนี้'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='approver_note',
            field=models.TextField(blank=True, help_text='หมายเหตุของผู้อนุมัติ'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='job_description',
            field=models.TextField(blank=True, help_text='คำอธิบายของตำแหน่งที่ผู้ใช้งานของผู้ใช้งานนี้'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='position',
            field=models.ForeignKey(blank=True, help_text='ตำแหน่งที่ผู้ใช้งานของผู้ใช้งานนี้', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='recruitment.jobposition'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='position_title',
            field=models.CharField(blank=True, help_text='ชื่อตำแหน่งที่ผู้ใช้งานของผู้ใช้งานนี้', max_length=200),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='priority',
            field=models.CharField(choices=[('urgent', 'ด่วน'), ('normal', 'ปกติ')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requester',
            field=models.ForeignKey(help_text='ผู้ขอสร้างใบนี้', on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='required_headcount',
            field=models.PositiveIntegerField(help_text='จำนวนคนที่ผู้ใช้งานของผู้ใช้งานนี้ของผู้ใช้งานนี้'),
        ),
        migrations.AlterField(
            model_name='user',
            name='approve_code',
            field=models.CharField(blank=True, help_text='person_unid ของผู้จัดการตรงของผู้ใช้งานนี้', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_code',
            field=models.CharField(blank=True, help_text='รหัสบริษัทของผู้ใช้งานนี้', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='แผนกของผู้ใช้งานนี้', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, help_text='ฝ่ายของผู้ใช้งานนี้', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, help_text='เพศของผู้ใช้งานนี้', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='สถานที่ของผู้ใช้งานนี้', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, help_text='ชื่อเล่นของผู้ใช้งานนี้', max_length=100),
        ),
        migrations.CreateModel(
            name='Acquaintance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อ-นามสกุล')),
                ('phone_number', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('relation', models.CharField(blank=True, choices=[('father', 'บิดา'), ('mother', 'มารดา'), ('relative', 'ญาติ'), ('sibling', 'พี่น้อง'), ('other', 'อื่นๆ')], max_length=20, null=True, verbose_name='ความสัมพันธ์')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquaintances', to='recruitment.candidate', verbose_name='ข้อมูลผู้สมัคร')),
            ],
            options={
                'verbose_name': 'บุคคลอ้างอิง/คนรู้จัก',
                'verbose_name_plural': 'บุคคลอ้างอิง/คนรู้จัก',
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อ-นามสกุล')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่ติดต่อ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('relation', models.CharField(blank=True, choices=[('father', 'บิดา'), ('mother', 'มารดา'), ('relative', 'ญาติ'), ('sibling', 'พี่น้อง'), ('other', 'อื่นๆ')], max_length=20, null=True, verbose_name='ความสัมพันธ์')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='recruitment.candidate', verbose_name='ข้อมูลผู้สมัคร')),
            ],
            options={
                'verbose_name': 'ผู้ค้ำประกัน',
                'verbose_name_plural': 'ผู้ค้ำประกัน',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสพนักงาน (ผูกเมื่อเสนอจ้าง)')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/', verbose_name='ไฟล์ Resume')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='portfolios/%Y/%m/', verbose_name='ไฟล์ Portfolio')),
                ('status', models.CharField(choices=[('applied', 'สมัครใหม่'), ('interviewing', 'นัดสัมภาษณ์'), ('not_selected', 'สัมภาษณ์ไม่ผ่าน'), ('offered', 'เสนอจ้างงาน'), ('hired', 'รับเข้าทำงาน'), ('rejected', 'ไม่มาทำงาน'), ('cancelled', 'ยกเลิก')], default='applied', max_length=20, verbose_name='สถานะใบสมัคร')),
                ('origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='แหล่งที่มา (เช่น JobThai)')),
                ('hr_note', models.TextField(blank=True, null=True, verbose_name='บันทึกจาก HR')),
                ('appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='วันเวลานัดสัมภาษณ์')),
                ('interviewer_names', models.CharField(blank=True, default='', max_length=255, verbose_name='ผู้สัมภาษณ์')),
                ('interviewer_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='อีเมลผู้สัมภาษณ์')),
                ('ccmail', models.CharField(blank=True, max_length=500, null=True, verbose_name='ccmail')),
                ('is_online', models.BooleanField(default=False, verbose_name='สัมภาษณ์ออนไลน์')),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='ลิงก์ประชุม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.candidate')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.requisition')),
            ],
            options={
                'verbose_name': 'ใบสมัครงาน',
                'verbose_name_plural': 'ใบสมัครงาน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='สถาบันที่จบ')),
                ('graduation', models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีที่จบ')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='เกรดเฉลี่ย (GPA)')),
                ('country', models.CharField(choices=[('thai', 'ไทย'), ('foreign', 'ต่างประเทศ')], default='thai', max_length=30, verbose_name='จบในประเทศไหน')),
                ('education', models.CharField(choices=[('middle_school', 'ระดับชั้นมัธยมศึกษาตอนต้น'), ('high_school', 'ระดับชั้นมัธยมศึกษาตอนปลาย'), ('vocational', 'ประกาศนียบัตรวิชาชีพ (ปวช.)'), ('higher_vocational', 'ประกาศนียบัตรวิชาชีพชั้นสูง (ปวส.)'), ('bachelor', 'ระดับปริญญาตรี'), ('master', 'ปริญญาโท'), ('doctorate', 'ปริญญาเอก')], max_length=100, verbose_name='ระดับการศึกษา')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='สาขาที่จบ')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='recruitment.candidate', verbose_name='ข้อมูลผู้สมัคร')),
            ],
            options={
                'verbose_name': 'ประวัติการศึกษา',
                'verbose_name_plural': 'ประวัติการศึกษา',
                'ordering': ['-graduation'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True, verbose_name='รหัสพนักงาน')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่มงาน')),
                ('is_active', models.BooleanField(default=False, verbose_name='สถานะยังทำงานอยู่')),
                ('resign_date', models.DateField(blank=True, null=True, verbose_name='วันที่ลาออก')),
                ('resign_note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุลาออก')),
                ('update_tiger_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_record', to='recruitment.candidate', verbose_name='ข้อมูลบุคคล')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.company', verbose_name='บริษัท')),
                ('employee_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.employeelevel', verbose_name='ระดับพนักงาน')),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hired_record', to='recruitment.jobapplication', verbose_name='อ้างอิงจากใบสมัคร')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.worklocation', verbose_name='สถานที่ทำงาน')),
            ],
            options={
                'verbose_name': 'ประวัติพนักงาน',
                'verbose_name_plural': 'ประวัติพนักงาน',
                'ordering': ['-start_date'],
            },
        ),
    ]
