# Generated by Django 5.1.15 on 2026-08-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_candidate_company_employeelevel_worklocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='อีเมล'),
        ),
    ]
