# Generated by Django 5.1.15 on 2026-08-16 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_jobapplication_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='เวลาเริ่มนัดหมาย')),
                ('end_time', models.DateTimeField(verbose_name='เวลาสิ้นสุดนัดหมาย')),
                ('interviewer_names', models.CharField(max_length=255, verbose_name='ผู้สัมภาษณ์')),
                ('cc_emails', models.CharField(blank=True, default='', max_length=500, verbose_name='อีเมล CC (คั่นด้วยจุลภาค)')),
                ('is_online', models.BooleanField(default=False, verbose_name='สัมภาษณ์ออนไลน์')),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='ลิงก์ประชุม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='recruitment.jobapplication', verbose_name='ใบสมัคร')),
            ],
            options={
                'verbose_name': 'นัดสัมภาษณ์',
                'verbose_name_plural': 'นัดสัมภาษณ์',
                'ordering': ['-start_time'],
            },
        ),
    ]
