# Generated by Django 5.1.15 on 2026-08-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='employee_code',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
